Improvements to mydocker wrapper script

diff --git a/mydocker b/mydocker
--- a/mydocker
+++ b/mydocker
@@ -5,6 +5,16 @@
 
 # Save the commands for debugging
 
+debug () {
+  if [ ! -z "$DEBUG_MYDOCK" ] ; then
+    echo "MYDOCK DEBUG: $@"
+  fi
+}
+
+error () {
+  echo "ERROR: $@" 1>&2
+}
+
 if [ "$1" = "pull" ] ;then
   echo $@ >> ~/mydocker.debug
   if [ $(shifterimg images|grep -c $2) -eq 0 ] ; then
@@ -13,43 +23,46 @@ if [ "$1" = "pull" ] ;then
 elif [ "$1" = "run" ] ;then
   echo $@ >> ~/mydocker.debug
   # KBase expects /kb/module to be writeable for now.  So let's make a copy for
-  # remounting rw
+  # remounting rw.  This has to be on a per job basis since configs get overwritten
   IMAGE=docker:$2
   MODULE=$(echo "$2"|sed 's|.*/||'|sed 's/:/_/')
-  RW=$SCRATCH/writeable/$MODULE
+  KB_JOBID=$(echo "$@"|sed 's|/job_.*||'|sed 's|.*/||')
+  debug "KBase JOBID: $KB_JOBID"
+  RW=$SCRATCH/writeable/${MODULE}-${DEPLOY}
   shifter --image=$IMAGE rsync -aqz /kb/module/ $RW
-  rmdir $RW/work
+  [ -d $RW/work ] && rmdir $RW/work
   ln -s /work $RW/work
 
   # Get the working directory
+  debug "VOLUME STRING: $5"
   VOLM=$(echo $5|sed 's|\[||'|sed 's|]||'|sed 's/:rw//g'|sed 's|/kb/module/work|/work|'|sed 's|/kb/module/work/tmp|/worktmp|'|sed 's/,/ --volume/g')
-  echo "DEBUG: $VOLM"  
-  echo "DEBUG: $5"
+  debug "$VOLM"  
   WD=$(echo $VOLM|sed 's/:.*//')/tmp
-  echo "Workdir:$WD"
-  echo "RW:$RW"
+  debug "Workdir:$WD"
+  debug "RW:$RW"
   # Run the job with basically no modifications
-  echo "shifter --image=$IMAGE  --volume $RW:/kb/module  --volume $VOLM $0 inside"
+  debug "shifter --image=$IMAGE  --volume $RW:/kb/module  --volume $VOLM $0 inside"
   shifter --image=$IMAGE \
     --volume $RW:/kb/module \
     --volume $VOLM $0 inside
 
   if [ $? -ne 0 ] ; then
-    echo "Job failed"
+    error "Job failed"
     exit $?
   fi
   # If this is an HPC job.  Let's submit the batch script
   # wait, then run post
   if [ -e $WD/slurm.submit ] ; then
+    echo "INFO: Submit script detected: Submitting job"
     export POST=1
     cd $WD
     export RUNDIR=$WD
     JOBID=$(sbatch -C haswell slurm.submit|sed 's/.* //')
     if [ $? -ne 0 ] ;then
-      echo "Submit Failed"
+      error "Submit Failed"
       exit 1
     fi
-    echo "Slurm Job ID: $JOBID"
+    echo "INFO: Slurm Job ID: $JOBID"
     squeue --job $JOBID
     echo "Waiting for job to complete"
     STATUS=$(squeue --job $JOBID -o '%t' -h)
@@ -57,16 +70,16 @@ elif [ "$1" = "run" ] ;then
       sleep 30
       STATUS=$(squeue --job $JOBID -o '%t' -h)
     done
-    shifter --image=$IMAGE \
+    exec shifter --image=$IMAGE \
       --volume $RW:/kb/module \
       --volume $VOLM $0 inside
   fi
 elif [ "$1" = "inside" ] ;then
   # This is needed because Shifter doesn't handle some docker metadata just yet (cwd)
-  echo "Inside Shifter wraper"
+  debug "Inside Shifter wraper"
   cd /kb/module
   if [ -e /worktmp ] ; then
-    mv /kb/module/work/tmp /kb/module/work/tmp.prev
+    [ -e /kb/module/work/tmp ] && mv /kb/module/work/tmp /kb/module/work/tmp.prev
     ln -s /worktmp /kb/module/work/tmp
   fi
   ./scripts/entrypoint.sh async
